#!/bin/bash
#
# Usage:
#
# $ cd dir_with_updated_d7
# $ d7-release
#
# This script assumes that ORIGIN points to pantheon-systems/drops-7
# and the current branch is a PR with a new version.
#
SELF_DIRNAME="`dirname -- "$0"`"

set -ex

# Get the current branch
branch=$(git rev-parse --abbrev-ref HEAD)

# If we're on the default branch, switch to master and pull.
if [ "$branch" == "default" ]
then
  git checkout master
  git pull origin master
  branch=master
fi

# Require the master branch
if [ "$branch" != "master" ]
then
  echo "Current branch must be master. Merge the update PR in GitHub before running this script."
  exit 1
fi

# Check the version of the current branch
version=$(drush status 'Drupal version' | sed -e 's/[^:]*: *//')

# Only release stable versions
set +e
non_stable=$(echo $version | grep -v '^v*[0-9.]*$')
set -e
if [ -n "$non_stable" ] ; then
  echo "Current version is $version; this script can only be used to releasese stable versions"
  echo 1
fi

# Check to see if there's already a tag for the current version
set +e
version_tag=$(git tag -l | grep "^$version\$")
set -e
if [ -n "$version_tag" ] ; then
  echo "Current release already tagged; nothing to do."
  exit 0
fi

# Delete all of the non-semver tags from the local repository to
# avoid conflicts when pushing
set +e
non_semver=$(git tag -l | grep -v '^v*[0-9.]*$')
set -e
for tag in $non_semver ; do
  git tag -d $tag
done

commit_message="$(git log --pretty=format:%s -1)"

# Add a note to the documentation changelog
$SELF_DIRNAME/update_changelog --fix --name=Drupal --project=pantheon-systems/drops-7 --version="$version" --message="$commit_message"

# Look up the release URL from the commit comment
release_url="$(echo "$commit_message" | sed -e 's#.*\(https://.*\)#\1#')"

# Post a security notification to statuspage if this is a security release
$SELF_DIRNAME/statuspage --release-url="$release_url"

git tag $version
git push origin master
git push origin $version

# Update the pantheon-systems/drops-7-composer version of
# this upstream, which squashes each release to one commit
# and adds a composer.json file.
$SELF_DIRNAME/create-composer-version-of-project d7

# Wait for Packagist to be updated with the new version created by the
# script above. If we do not wait, our call to composer-lock-update
# will not see our latest update.
$SELF_DIRNAME/wait-for-packagist pantheon-systems/drops-7-composer $version

# Make a PR to update the example-drops-7-composer composer.lock file.
clu pantheon-systems/example-drops-7-composer

