#!/bin/bash
#
# Usage:
#
# $ cd dir_with_updated_wp
# $ wp-release
#
# This script assumes that ORIGIN points to pantheon-systems/WordPress
# and the current branch is master with the current release already merged.
#
SELF_DIRNAME="`dirname -- "$0"`"

set -ex

# Get the current branch
branch=$(git rev-parse --abbrev-ref HEAD)

# If we're on the default branch, switch to master and pull.
if [ "$branch" == "default" ]
then
  git checkout master
  git pull origin master
  branch=master
fi

# Require the master branch
if [ "$branch" != "master" ]
then
  echo "Current branch must be master. Merge the update PR in GitHub before running this script."
  exit 1
fi

# Check the version of the current branch
version=$(wp core version)

# Only release stable versions
set +e
non_stable=$(echo $version | grep -v '^v*[0-9.]*$')
set -e
if [ -n "$non_stable" ] ; then
  echo "Current version is $version; this script can only be used to releasese stable versions"
  echo 1
fi

# Check to see if there's already a tag for the current version
set +e
version_tag=$(git tag -l | grep "^$version\$")
set -e

git tag $version
git push origin $version

# Add a note to the documentation changelog
$SELF_DIRNAME/update_changelog --fix --name=WordPress --project=pantheon-systems/WordPress --version="$version" --message="$commit_message"

# Add a remote for wordpress-network if it's not already there.
set +e
has_remote=$(git remote show | grep wordpress-network 2>/dev/null)
set -e
if [ -z "$has_remote" ] ; then
  git remote add wordpress-network git@github.com:pantheon-systems/wordpress-network.git
fi

# Release on wordpress-network too
git push wordpress-network master
git push wordpress-network $version

# Update the pantheon-systems/wordpress-composer version of
# this upstream, which squashes each release to one commit
# and adds a composer.json file.
$SELF_DIRNAME/create-composer-version-of-project wp

# Wait for Packagist to be updated with the new version created by the
# script above. If we do not wait, our call to composer-lock-update
# will not see our latest update.
$SELF_DIRNAME/wait-for-packagist pantheon-systems/wordpress-composer $version

# Make a PR to update the example-wordpress-composer composer.lock file.
clu pantheon-systems/example-wordpress-composer

$SELF_DIRNAME/statuspage --release-url="$release_url" --version="$version_tag" --simulate
